In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!git clone 'https://github.com/AliM100/Ransomware_Detection.git'
!pip install patool

In [ ]:
!unzip /content/drive/MyDrive/malimg_dataset.zip -d data

In [5]:
import os
import sys
import os
from math import log
import numpy as np
import scipy as sp
from PIL import Image
import matplotlib.pyplot as plt
import cv2
import shutil
import pandas as pd
import patoolib
import seaborn as sns
from torch.utils.tensorboard import SummaryWriter
from datetime import datetime
from sklearn import metrics
from sklearn.metrics import average_precision_score,accuracy_score
from torch.optim.lr_scheduler import ReduceLROnPlateau
import tensorflow
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision
from Ransomware_Detection.mal_dataset import maldataset
from Ransomware_Detection.data_conversion import convert_data
from Ransomware_Detection.dataset import load_data,prepare_data


In [6]:
class_index = {'Adialer.C': 0,
                'Agent.FYI': 1,
                'Allaple.A': 2,
                'Allaple.L': 3,
                'Alueron.gen!J': 4,
                'Autorun.K': 5,
                'C2LOP.P': 6,
                'C2LOP.gen!g': 7,
                'Dialplatform.B': 8,
                'Dontovo.A': 9,
                'Fakerean': 10,
                'Instantaccess': 11,
                'Lolyda.AA1': 12,
                'Lolyda.AA2': 13,
                'Lolyda.AA3': 14,
                'Lolyda.AT': 15,
                'Malex.gen!J': 16,
                'Obfuscator.AD': 17,
                'Rbot!gen': 18,
                'Skintrim.N': 19,
                'Swizzor.gen!E': 20,
                'Swizzor.gen!I': 21,
                'VB.AT': 22,
                'Wintrim.BX': 23,
                'Yuner.A': 24}



In [7]:
data_path="data"
img_path="data/malimg_paper_dataset_imgs"
data_csvs="data/csvs"
save_checkpoints_path="data/checkpoint"
batch_size= 10

os.makedirs(save_checkpoints_path,exist_ok=True)
os.makedirs(data_csvs,exist_ok=True)

data_prepare=prepare_data(data_path,img_path,class_index)

if not os.path.exists(f"{data_csvs}/train.csv"):
    data_prepare.create_csv_data()

target_size_custom = (224, 224)

transform = transforms.Compose([
    transforms.Resize(target_size_custom),
    # transforms.Grayscale(num_output_channels=1),
    transforms.Lambda(lambda x: x.float()),
    transforms.Normalize((0.5,), (0.5,))])

training_set=maldataset(csv_file=f"{data_csvs}/train.csv",root_dir=img_path, class_index=class_index, transform=transform)
validation_set=maldataset(csv_file=f"{data_csvs}/val.csv",root_dir=img_path, class_index=class_index, transform=transform)

training_loader = torch.utils.data.DataLoader(training_set, batch_size=batch_size, shuffle=True)
validation_loader = torch.utils.data.DataLoader(validation_set, batch_size=batch_size, shuffle=False)


classes = ('Adialer.C','Agent.FYI','Allaple.A','Allaple.L','Alueron.gen!J','Autorun.K','C2LOP.P','C2LOP.gen!g','Dialplatform.B','Dontovo.A',
           'Fakerean','Instantaccess','Lolyda.AA1','Lolyda.AA2','Lolyda.AA3','Lolyda.AT','Malex.gen!J','Obfuscator.AD','Rbot!gen','Skintrim.N',
           'Swizzor.gen!E','Swizzor.gen!I','VB.AT','Wintrim.BX','Yuner.A')


Adialer.C (74, 2) (24, 2) 122
Agent.FYI (70, 2) (23, 2) 116
Allaple.A (1771, 2) (589, 2) 2949
Allaple.L (955, 2) (318, 2) 1591
Alueron.gen!J (120, 2) (39, 2) 198
Autorun.K (64, 2) (21, 2) 106
C2LOP.P (88, 2) (29, 2) 146
C2LOP.gen!g (120, 2) (40, 2) 200
Dialplatform.B (107, 2) (35, 2) 177
Dontovo.A (98, 2) (32, 2) 162
Fakerean (229, 2) (76, 2) 381
Instantaccess (259, 2) (86, 2) 431
Lolyda.AA1 (129, 2) (42, 2) 213
Lolyda.AA2 (112, 2) (36, 2) 184
Lolyda.AA3 (75, 2) (24, 2) 123
Lolyda.AT (97, 2) (31, 2) 159
Malex.gen!J (82, 2) (27, 2) 136
Obfuscator.AD (86, 2) (28, 2) 142
Rbot!gen (96, 2) (31, 2) 158
Skintrim.N (48, 2) (16, 2) 80
Swizzor.gen!E (78, 2) (25, 2) 128
Swizzor.gen!I (80, 2) (26, 2) 132
VB.AT (246, 2) (81, 2) 408
Wintrim.BX (59, 2) (19, 2) 97
Yuner.A (480, 2) (160, 2) 800


In [8]:
import torch
import torch.nn as nn
####best model of the best 97.9 accuracy on malimg 25 classes
###dropout 0.25 -> 0.01 accuracy 97.85
### single linear layer maybe better choice
class CustomModel(nn.Module):
    def __init__(self, num_classes=26):
        super(CustomModel, self).__init__()

        self.conv1 = nn.Conv2d(1, 64, kernel_size=(3, 3), stride=1, padding=1)
        self.pool1 = nn.MaxPool2d(kernel_size=(2, 2), stride=2)
        self.batch_norm1 = nn.BatchNorm2d(64)

        self.conv2 = nn.Conv2d(64, 32, kernel_size=(3, 3), stride=1, padding=1)
        self.pool2 = nn.MaxPool2d(kernel_size=(2, 2), stride=2)
        self.batch_norm2 = nn.BatchNorm2d(32)

        self.conv3 = nn.Conv2d(32, 32, kernel_size=(3, 3), stride=1, padding=1)
        self.pool3 = nn.MaxPool2d(kernel_size=(2, 2), stride=2)
        self.batch_norm3 = nn.BatchNorm2d(32)

        self.conv4 = nn.Conv2d(32, 16, kernel_size=(3, 3), stride=1, padding=1)
        self.pool4 = nn.MaxPool2d(kernel_size=(2, 2), stride=2)
        self.batch_norm4 = nn.BatchNorm2d(16)

        self.conv5 = nn.Conv2d(16, 16, kernel_size=(3, 3), stride=1, padding=1)
        self.pool5 = nn.MaxPool2d(kernel_size=(2, 2), stride=2)
        self.batch_norm5 = nn.BatchNorm2d(16)


        self.flatten = nn.Flatten()

        self.fc1_input_size = 16 * (target_size_custom[0] // 32) * (target_size_custom[1] // 32)
        self.fc1 = nn.Linear(self.fc1_input_size, 256)
        self.dropout1 = nn.Dropout(0.25)
        self.batch_norm_fc1 = nn.BatchNorm1d(256)

        self.fc2 = nn.Linear(256, 128)
        self.dropout2 = nn.Dropout(0.25)
        self.batch_norm_fc2 = nn.BatchNorm1d(128)

        self.fc3 = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.batch_norm1(self.pool1(torch.relu(self.conv1(x))))
        x = self.batch_norm2(self.pool2(torch.relu(self.conv2(x))))
        x = self.batch_norm3(self.pool3(torch.relu(self.conv3(x))))
        x = self.batch_norm4(self.pool4(torch.relu(self.conv4(x))))
        x = self.batch_norm5(self.pool5(torch.relu(self.conv5(x))))

        x = self.flatten(x)

        x = self.batch_norm_fc1(self.dropout1(torch.relu(self.fc1(x))))
        x = self.batch_norm_fc2(self.dropout2(torch.relu(self.fc2(x))))
        x = self.fc3(x)

        return x

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)


model = CustomModel(num_classes=25).to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001, weight_decay=5e-4)


def update_lr(optimizer, lr):
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr

cuda


In [10]:
def train_one_epoch(epoch_index, tb_writer):
    running_loss = 0.
    last_loss = 0.
    all_true_labels = []
    all_predicted_labels = []
    # Here, we use enumerate(training_loader) instead of
    # iter(training_loader) so that we can track the batch
    # index and do some intra-epoch reporting

    for i, data in enumerate(training_loader):
        # Every data instance is an input + label pair
        inputs, labels = data
        inputs, labels = inputs.to(device), labels.to(device)
        # Zero your gradients for every batch!
        optimizer.zero_grad()

        # Make predictions for this batch
        outputs = model(inputs.float())

        # Compute the loss and its gradients
        loss = loss_fn(outputs, labels)
        loss.backward()

        # Adjust learning weights
        optimizer.step()

        # Gather data and report
        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        all_true_labels.extend(labels.cpu().numpy())
        all_predicted_labels.extend(predicted.cpu().numpy())

        if i % 1000 == 999:
            last_loss = running_loss / 1000 # loss per batch
            print('  batch {} loss: {}'.format(i + 1, last_loss))
            tb_x = epoch_index * len(training_loader) + i + 1
            tb_writer.add_scalar('Loss/train', last_loss, tb_x)
            running_loss = 0.

    # scheduler.step(loss)
    train_accuracy = accuracy_score(all_true_labels, all_predicted_labels)

    return last_loss, train_accuracy

In [11]:
# Initializing in a separate cell so we can easily add more epochs to the same run
checkpoint="checkpoints"
os.makedirs(checkpoint,exist_ok=True)
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
writer = SummaryWriter('runs/trainer_{}'.format(timestamp))
epoch_number = 0

EPOCHS = 100

best_vloss = 1_000_000.
best_accuracy=0
for epoch in range(EPOCHS):
    print('EPOCH {}:'.format(epoch_number + 1))

    # Make sure gradient tracking is on, and do a pass over the data
    model.train(True)
    avg_loss, train_accuracy = train_one_epoch(epoch_number, writer)


    running_vloss = 0.0
    # Set the model to evaluation mode, disabling dropout and using population
    # statistics for batch normalization.
    model.eval()
    val_true_labels = []
    val_predicted_labels = []
    # Disable gradient computation and reduce memory consumption.
    with torch.no_grad():
        for i, vdata in enumerate(validation_loader):
            vinputs, vlabels = vdata
            vinputs, vlabels = vinputs.to(device), vlabels.to(device)
            voutputs = model(vinputs.float())
            vloss = loss_fn(voutputs, vlabels)
            running_vloss += vloss

            _, predicted = torch.max(voutputs, 1)
            val_true_labels.extend(vlabels.cpu().numpy())
            val_predicted_labels.extend(predicted.cpu().numpy())


    avg_vloss = running_vloss / (i + 1)
    val_accuracy = accuracy_score(val_true_labels, val_predicted_labels)

    print('LOSS train {} valid {}'.format(avg_loss, avg_vloss))
    print('Accuracy train {} valid {}'.format(train_accuracy, val_accuracy))

    # Log the running loss averaged per batch
    # for both training and validation
    writer.add_scalars('Training vs. Validation Loss',
                    { 'Training' : avg_loss, 'Validation' : avg_vloss },
                    epoch_number + 1)
    writer.add_scalars('Training vs. Validation Accuracy',
                { 'Training' : train_accuracy, 'Validation' : val_accuracy },
                epoch_number + 1)
    writer.flush()

    # Track best performance, and save the model's state
    if val_accuracy > best_accuracy :#or avg_vloss < best_vloss:
        #best_vloss = avg_vloss
        best_accuracy = val_accuracy
        model_path = 'checkpoints/model_{}_{}'.format(timestamp, epoch_number)
        torch.save(model.state_dict(), model_path)

    epoch_number += 1

EPOCH 1:
LOSS train 0.0 valid 0.6313334107398987
Accuracy train 0.6823759558954294 valid 0.9133476856835306
EPOCH 2:
LOSS train 0.0 valid 0.3874874711036682
Accuracy train 0.8669749244175707 valid 0.9456404736275565
EPOCH 3:
LOSS train 0.0 valid 0.21297726035118103
Accuracy train 0.9151698381646808 valid 0.9531754574811625
EPOCH 4:
LOSS train 0.0 valid 0.15660953521728516
Accuracy train 0.9381113284723457 valid 0.9677072120559742
EPOCH 5:
LOSS train 0.0 valid 0.13065221905708313
Accuracy train 0.945758491908234 valid 0.9671689989235738
EPOCH 6:
LOSS train 0.0 valid 0.10234937071800232
Accuracy train 0.951627245242753 valid 0.9671689989235738
EPOCH 7:
LOSS train 0.0 valid 0.09679097682237625
Accuracy train 0.9583852036279566 valid 0.9736275565123789
EPOCH 8:
LOSS train 0.0 valid 0.08686784654855728
Accuracy train 0.9631869109016539 valid 0.9693218514531755
EPOCH 9:
LOSS train 0.0 valid 0.07999642193317413
Accuracy train 0.9596300906989151 valid 0.9703982777179763
EPOCH 10:
LOSS train 0.

In [13]:
%tensorboard --logdir runs

UsageError: Line magic function `%tensorboard` not found.


In [14]:
transform = transforms.Compose([
    transforms.Resize(target_size_custom),
    # transforms.Grayscale(num_output_channels=1),
    transforms.Lambda(lambda x: x.float()),
    transforms.Normalize((0.5,), (0.5,))
    ])

test_set=maldataset(csv_file=f"{data_csvs}/test.csv",root_dir=img_path, class_index=class_index, transform=transform)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False)


model = CustomModel(num_classes=25).to(device)
model.load_state_dict(torch.load("checkpoints/model_20240319_110832_37"), strict=False)

running_testloss=0.0
model.eval()
test_true_labels = []
test_predicted_labels = []
with torch.no_grad():
    for i, data in enumerate(test_loader):
        # Every data instance is an input + label pair
        inputs, labels = data
        inputs, y_gt = inputs.to(device), labels.to(device)

        y_test_predicted = model(inputs.float())
        test_loss = loss_fn(y_test_predicted, y_gt)
        print(test_loss)
        running_testloss += test_loss.item()

        _, predicted = torch.max(y_test_predicted, 1)
        print(predicted)
        test_true_labels.extend(labels.cpu().numpy())
        test_predicted_labels.extend(predicted.cpu().numpy())

    avg_testloss = running_testloss / (i + 1)
    test_accuracy = accuracy_score(test_true_labels, test_predicted_labels)

    IoU=metrics.jaccard_score(test_true_labels, test_predicted_labels,average="micro")
    f1=metrics.f1_score(test_true_labels, test_predicted_labels,average="micro")
    print("micro IoU",IoU)
    print("micro f1",f1)

    IoU=metrics.jaccard_score(test_true_labels, test_predicted_labels,average="macro")
    f1=metrics.f1_score(test_true_labels, test_predicted_labels,average="macro")
    print("macro IoU",IoU)
    print("macro f1",f1)

    print('LOSS test{}, Accuracy test{}'.format(avg_testloss,test_accuracy))



tensor(0.0001, device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor(8.4479e-05, device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor(0.0021, device='cuda:0')
tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 1], device='cuda:0')
tensor(0.0004, device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
tensor(0.0027, device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 2, 2, 2], device='cuda:0')
tensor(0.0006, device='cuda:0')
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], device='cuda:0')
tensor(0.0007, device='cuda:0')
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], device='cuda:0')
tensor(0.0007, device='cuda:0')
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], device='cuda:0')
tensor(0.0006, device='cuda:0')
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], device='cuda:0')
tensor(0.0006, device='cuda:0')
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], device='cuda:0')
tensor(0.0007, device='cuda:0')
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], device='cuda:0')
tensor(0.0007, device='cuda:

In [ ]:
def confusion_matrix(confusion_matrix, class_names, figsize = (10,7), fontsize=14):
    df_cm = pd.DataFrame(
        confusion_matrix, index=class_names, columns=class_names,
    )
    fig = plt.figure(figsize=figsize)
    try:
        heatmap = sns.heatmap(df_cm, annot=True, fmt="d")
    except ValueError:
        raise ValueError("Confusion matrix values must be integers.")
    heatmap.yaxis.set_ticklabels(heatmap.yaxis.get_ticklabels(), rotation=0, ha='right', fontsize=fontsize)
    heatmap.xaxis.set_ticklabels(heatmap.xaxis.get_ticklabels(), rotation=45, ha='right', fontsize=fontsize)
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [ ]:
c_matrix = metrics.confusion_matrix(test_true_labels, test_predicted_labels)
df_confusion = pd.crosstab(test_true_labels, test_predicted_labels)
df_confusion.to_csv(os.path.join(data_path,"confusion_matrix.csv"))

confusion_matrix(c_matrix, classes, figsize = (20,7), fontsize=14)

In [ ]:
report = metrics.classification_report(test_true_labels, test_predicted_labels, target_names=classes,  output_dict=True)
df_report = pd.DataFrame(report).transpose()
print(df_report)